name: Python package

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read  # Allow read-only access to repository contents (default for most jobs)
  pull-requests: write  # Allow write access for pull requests, if necessary

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]  # You can add more versions here if needed

    permissions:
      contents: read  # Read access to repository contents (needed for checking out code)
      pull-requests: write  # Write access to pull requests (if needed, can be reduced)
    
    steps:
    - uses: actions/checkout@v4  # Checkout the repository's code
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip  # Upgrade pip
        python -m pip install flake8 pytest  # Install flake8 and pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi  # Install dependencies from requirements.txt if present
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings, adjust complexity and max-line-length settings
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

  my-job:
    permissions:
      contents: read  # Read access to repository contents
      pull-requests: write  # Write access to pull requests (adjust if not necessary)
    runs-on: ubuntu-latest
    steps:
      - name: Example step for my-job
        run: echo "This is a placeholder job"
